version: "3.9"
services:
  magic-nights:
    build: .
    ports:
      - "8080:8080"
    networks:
      default:
        ipv4_address: 192.168.2.2

networks:
  default:
    name: magicnet
    external: true
    ipam:
      config:
        - subnet: 192.168.2.0/24