version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: magicnights_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=magicnights
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
#      - ./init_db.sh:/docker-entrypoint-initdb.d/01_init_db.sh
  mongo-db:
    image: mongo:latest
    container_name: mongo-magicnights
    hostname: host-mongo-magicnights

    ports:
      - "27016:27017"
    volumes:
      - ~/mongo/magicnights_db:/data/db
      - ~/mongo/magicnights_log:/var/log/mongodb/
      - ./Docker/mongo-init.js:/docker-entrypoint-initdb.d/01-mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: magicnights

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mad@mail.com
      PGADMIN_DEFAULT_PASSWORD: asdf
    volumes:
      - pgadmin-data:/var/lib/pgadmin

#  magic-nights:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on: [db,pgadmin]

volumes:
  db:
  pgadmin-data: