server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: never

spring:
  application:
    name: magicnights
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: baseBootstrap

  security:
    user:
      name: user
      password: usersinpass

  #   base de datos posta
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/magicnights
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: mongodb://admin:admin@127.0.0.1:27016/magicnights?authSource=admin

# Para activar el Trace
logging:
  level:
    root: INFO
    org.springframework.data: DEBUG
    org.mongodb.driver.protocol.command: DEBUG

# Rutas default para los endpoints
api:
  base: /api
  ticket: ${api.base}/ticket
  user: ${api.base}/user
  show: ${api.base}/show
  cart: ${api.base}/cart
  showdate: ${api.base}/showdate
  comment: ${api.base}/comment