server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: never

spring:
  application:
    name: magicnights
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: baseBootstrap

  security:
    user:
      name: user
      password: usersinpass

  #   base de datos posta
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/magicnights
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      #uri: mongodb://admin:admin@localhost:27017,localhost:27018,localhost:27019/magicnights?readPreference=primary&replicaSet=mnrs&authSource=admin
      uri: mongodb://admin:admin@localhost:27017/magicnights?authSource=admin
# Para activar el Trace
logging:
  level:
    root: INFO
    org.springframework.data: DEBUG
    org.mongodb.driver.protocol.command: DEBUG