version: "3.9"
services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    restart: always
    expose:
      - "27058"
    ports:
      - "27058:27017"
    networks:
      mn-net:
        ipv4_address: 172.16.238.10
    volumes:
      - mongo-data1:/data/db
      - mongo-cfg1:/data/configdb
      - mongo-log1:/var/log/mongodb
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
      - ./scripts/init.js:/scripts/init.js
      - ./scripts/init.js:/docker-entrypoint-initdb.d/01-init-mongo.js:ro
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: admin
      #MONGO_INITDB_ROOT_PASSWORD: admin
      #MONGO_INITDB_DATABASE: magicnights
    depends_on:
      - mongo2
      - mongo3
    links:
      - mongo2
      - mongo3
    entrypoint: ["sh", "-c", "chmod +x /scripts/rs-init.sh && /usr/bin/mongod --bind_ip_all --replSet mnrs"]

  mongo2:
    image: mongo:latest
    container_name: mongo2
    restart: always
    expose:
      - "27059"
    ports:
      - "27059:27017"
    networks:
      mn-net:
        ipv4_address: 172.16.238.11
    volumes:
      - mongo-data2:/data/db
      - mongo-cfg2:/data/configdb
      - mongo-log2:/var/log/mongodb
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "mnrs"]

  mongo3:
    image: mongo:latest
    container_name: mongo3
    restart: always
    expose:
      - "27060"
    ports:
      - "27060:27017"
    networks:
      mn-net:
        ipv4_address: 172.16.238.12
    volumes:
      - mongo-data3:/data/db
      - mongo-cfg3:/data/configdb
      - mongo-log3:/var/log/mongodb
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "mnrs"]

volumes:
  mongo-data1:
    driver: local
  mongo-cfg1:
    driver: local
  mongo-log1:
    driver: local
  mongo-data2:
    driver: local
  mongo-cfg2:
    driver: local
  mongo-log2:
      driver: local
  mongo-data3:
    driver: local
  mongo-cfg3:
    driver: local
  mongo-log3:
    driver: local

networks:
  mn-net:
    name: mn-net
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24