version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=magicnights
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    networks:
      default:
        ipv4_address: 172.16.238.202
    volumes:
      - postgres-data:/var/lib/postgresql/data
  #      - ./init_db.sh:/docker-entrypoint-initdb.d/01_init_db.sh

volumes:
  postgres-data:
    driver: local

networks:
  default:
    name: mn-net
    external: true
    ipam:
      config:
        - subnet: 172.16.238.0/24